INSERT INTO tb_cm_menu (prnt_menu_cd, menu_cd,pgm_id, ord , menu_kind, menu_lvl, menu_nm, menu_path,  rmk, crt_user_no, updt_user_no, crt_dtm, updt_dtm) VALUES (null        ,'MN_CM_0000',''       ,'00000',  'M', '0', '시스템관리', '시스템관리',   null, 0, 0, NOW(), NOW()) ON CONFLICT (menu_cd) DO NOTHING;        


INSERT INTO tb_cm_menu (prnt_menu_cd, menu_cd,pgm_id, ord , menu_kind, menu_lvl, menu_nm, menu_path,  rmk, crt_user_no, updt_user_no, crt_dtm, updt_dtm) VALUES ('MN_CM_0000','MN_CM_1000',''       ,'01000',  'M', '1', '시스템', '시스템관리>시스템',   null, 0, 0, NOW(), NOW()) ON CONFLICT (menu_cd) DO NOTHING;            
INSERT INTO tb_cm_menu (prnt_menu_cd, menu_cd,pgm_id, ord , menu_kind, menu_lvl, menu_nm, menu_path,  rmk, crt_user_no, updt_user_no, crt_dtm, updt_dtm) VALUES ('MN_CM_1000','MN_CM_1100','CM_1100','01100',  'S', '2', '프로그램관리', '시스템관리>시스템>프로그램관리',   null, 0, 0, NOW(), NOW()) ON CONFLICT (menu_cd) DO NOTHING;            
INSERT INTO tb_cm_menu (prnt_menu_cd, menu_cd,pgm_id, ord , menu_kind, menu_lvl, menu_nm, menu_path,  rmk, crt_user_no, updt_user_no, crt_dtm, updt_dtm) VALUES ('MN_CM_1000','MN_CM_1200','CM_1200','01200',  'S', '2', '테이블도메인관리', '시스템관리>시스템>테이블도메인관리',   null, 0, 0, NOW(), NOW()) ON CONFLICT (menu_cd) DO NOTHING;            
INSERT INTO tb_cm_menu (prnt_menu_cd, menu_cd,pgm_id, ord , menu_kind, menu_lvl, menu_nm, menu_path,  rmk, crt_user_no, updt_user_no, crt_dtm, updt_dtm) VALUES ('MN_CM_1000','MN_CM_1300','CM_1300','01300',  'S', '2', '메뉴관리', '시스템관리>시스템>메뉴관리',   null, 0, 0, NOW(), NOW())   ON CONFLICT (menu_cd) DO NOTHING;           
INSERT INTO tb_cm_menu (prnt_menu_cd, menu_cd,pgm_id, ord , menu_kind, menu_lvl, menu_nm, menu_path,  rmk, crt_user_no, updt_user_no, crt_dtm, updt_dtm) VALUES ('MN_CM_1000','MN_CM_1400','CM_1400','01400',  'S', '2', '공통코드관리', '시스템관리>시스템>공통코드관리',   null, 0, 0, NOW(), NOW()) ON CONFLICT (menu_cd) DO NOTHING;            
INSERT INTO tb_cm_menu (prnt_menu_cd, menu_cd,pgm_id, ord , menu_kind, menu_lvl, menu_nm, menu_path,  rmk, crt_user_no, updt_user_no, crt_dtm, updt_dtm) VALUES ('MN_CM_1000','MN_CM_1600','CM_1600','01600',  'S', '2', '테이블시퀀스', '시스템관리>시스템>테이블시퀀스',   null, 0, 0, NOW(), NOW()) ON CONFLICT (menu_cd) DO NOTHING;            
INSERT INTO tb_cm_menu (prnt_menu_cd, menu_cd,pgm_id, ord , menu_kind, menu_lvl, menu_nm, menu_path,  rmk, crt_user_no, updt_user_no, crt_dtm, updt_dtm) VALUES ('MN_CM_1000','MN_CM_1840','CM_1840','01840',  'S', '2', 'SA에러로그', '시스템관리>시스템>SA에러로그',   null, 0, 0, NOW(), NOW()) ON CONFLICT (menu_cd) DO NOTHING;            
INSERT INTO tb_cm_menu (prnt_menu_cd, menu_cd,pgm_id, ord , menu_kind, menu_lvl, menu_nm, menu_path,  rmk, crt_user_no, updt_user_no, crt_dtm, updt_dtm) VALUES ('MN_CM_1000','MN_CM_1850','CM_1850','01850',  'S', '2', '로그LIST', '시스템관리>시스템>로그LIST',   null, 0, 0, NOW(), NOW()) ON CONFLICT (menu_cd) DO NOTHING;            

INSERT INTO tb_cm_menu (prnt_menu_cd, menu_cd,pgm_id, ord , menu_kind, menu_lvl, menu_nm, menu_path,  rmk, crt_user_no, updt_user_no, crt_dtm, updt_dtm) VALUES ('MN_CM_0000','MN_CM_2000',''       ,'04000',  'M', '1', '회원관리', '시스템관리>회원관리',   null, 0, 0, NOW(), NOW()) ON CONFLICT (menu_cd) DO NOTHING;            
INSERT INTO tb_cm_menu (prnt_menu_cd, menu_cd,pgm_id, ord , menu_kind, menu_lvl, menu_nm, menu_path,  rmk, crt_user_no, updt_user_no, crt_dtm, updt_dtm) VALUES ('MN_CM_2000','MN_CM_4100','CM_4100','04100',  'S', '2', '회원관리', '시스템관리>회원관리>회원관리',   null, 0, 0, NOW(), NOW()) ON CONFLICT (menu_cd) DO NOTHING;            
INSERT INTO tb_cm_menu (prnt_menu_cd, menu_cd,pgm_id, ord , menu_kind, menu_lvl, menu_nm, menu_path,  rmk, crt_user_no, updt_user_no, crt_dtm, updt_dtm) VALUES ('MN_CM_2000','MN_CM_4200','CM_4200','04200',  'S', '2', '역할관리', '시스템관리>회원관리>역할관리',   null, 0, 0, NOW(), NOW()) ON CONFLICT (menu_cd) DO NOTHING;            

INSERT INTO tb_cm_menu (prnt_menu_cd, menu_cd,pgm_id, ord , menu_kind, menu_lvl, menu_nm, menu_path,  rmk, crt_user_no, updt_user_no, crt_dtm, updt_dtm) VALUES ('MN_CM_0000','MN_CM_3000',''       ,'06000',  'M', '1', 'DEV', '시스템관리>DEV',   null, 0, 0, NOW(), NOW()) ON CONFLICT (menu_cd) DO NOTHING;            
INSERT INTO tb_cm_menu (prnt_menu_cd, menu_cd,pgm_id, ord , menu_kind, menu_lvl, menu_nm, menu_path,  rmk, crt_user_no, updt_user_no, crt_dtm, updt_dtm) VALUES ('MN_CM_3000','MN_CM_6100','CM_6100','06100',  'S', '2', '게시판관리', '시스템관리>DEV>게시판관리',   null, 0, 0, NOW(), NOW()) ON CONFLICT (menu_cd) DO NOTHING;            
INSERT INTO tb_cm_menu (prnt_menu_cd, menu_cd,pgm_id, ord , menu_kind, menu_lvl, menu_nm, menu_path,  rmk, crt_user_no, updt_user_no, crt_dtm, updt_dtm) VALUES ('MN_CM_3000','MN_CM_6200','CM_6200','06200',  'S', '2', '게시판', '시스템관리>DEV>게시판',   null, 0, 0, NOW(), NOW()) ON CONFLICT (menu_cd) DO NOTHING;            
INSERT INTO tb_cm_menu (prnt_menu_cd, menu_cd,pgm_id, ord , menu_kind, menu_lvl, menu_nm, menu_path,  rmk, crt_user_no, updt_user_no, crt_dtm, updt_dtm) VALUES ('MN_CM_3000','MN_CM_7100','CM_7100','07100',  'S', '2', '테이블관리', '시스템관리>DEV>테이블관리',   null, 0, 0, NOW(), NOW())    ON CONFLICT (menu_cd) DO NOTHING;            
INSERT INTO tb_cm_menu (prnt_menu_cd, menu_cd,pgm_id, ord , menu_kind, menu_lvl, menu_nm, menu_path,  rmk, crt_user_no, updt_user_no, crt_dtm, updt_dtm) VALUES ('MN_CM_3000','MN_CM_7200','CM_7200','07200',  'S', '2', '컬럼상세', '시스템관리>DEV>컬럼상세',   null, 0, 0, NOW(), NOW())  ON CONFLICT (menu_cd) DO NOTHING;            
INSERT INTO tb_cm_menu (prnt_menu_cd, menu_cd,pgm_id, ord , menu_kind, menu_lvl, menu_nm, menu_path,  rmk, crt_user_no, updt_user_no, crt_dtm, updt_dtm) VALUES ('MN_CM_3000','MN_CM_7300','CM_7300','07300',  'S', '2', 'SQL', '시스템관리>DEV>SQL',   null, 0, 0, NOW(), NOW())  ON CONFLICT (menu_cd) DO NOTHING;            