server.port: 7090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.0.13/stockweb
    username: postgres
    password: POSTGRES
  jackson:
    serialization:
      write-dates-as-timestamps: false
  jpa:
    hibernate:
      ddl-auto: create-drop
  batch.job.enabled: false # CommandLineRunner 설정 해제      

logging:
  config: classpath:logback-spring.xml 

env:
  serverfilepath: /home/jijs/avdbs.com
  apiurl: http://demoJpa:8091/api/
  apiurlbizactor: http://192.168.0.13:18080/bizarest_v2/
  apiurllog: http://192.168.0.13:18080/log/
  timeout: 3600 #초위 10==>  10초 